import type { SynthPatch } from "./types";

export const defaultPatch: SynthPatch = {
  version: 1,
  name: "ALGORITHMIC PIANO",
  routing: {
    connections: [
      { from: "op1", to: "op2" },
      { from: "op3", to: "op4" },
      { from: "op2", to: "output" },
      { from: "op4", to: "output" },
    ],
  },
  masterGain: 0.76,
  operators: [
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 2,
      fixedHz: 440,
      detune: 0,
      level: 0.42,
      modulationIndex: 1.2,
      feedback: 0,
      envelope: {
        attack: 0,
        segment1Time: 0.28,
        segment1Level: 0.36,
        segment2Time: 0.57,
        segment2Level: 0.08,
        release: 0.4,
      },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 1,
      fixedHz: 440,
      detune: 0,
      level: 0.95,
      modulationIndex: 0,
      feedback: 0,
      envelope: {
        attack: 0.003,
        segment1Time: 0.42,
        segment1Level: 0.62,
        segment2Time: 1.38,
        segment2Level: 0.32,
        release: 1,
      },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 3,
      fixedHz: 440,
      detune: 0,
      level: 0.28,
      modulationIndex: 1.45,
      feedback: 0,
      envelope: {
        attack: 0,
        segment1Time: 0.06,
        segment1Level: 0.18,
        segment2Time: 0.12,
        segment2Level: 0,
        release: 0.12,
      },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 1,
      fixedHz: 440,
      detune: 3,
      level: 0.32,
      modulationIndex: 0,
      feedback: 0,
      envelope: {
        attack: 0.002,
        segment1Time: 0.14,
        segment1Level: 0.26,
        segment2Time: 0.51,
        segment2Level: 0.08,
        release: 0.55,
      },
    },
  ],
};
