import type { SynthPatch } from "./types";

export const defaultPatch: SynthPatch = {
  version: 1,
  name: "ALGORITHMIC PIANO",
  routing: {
    connections: [
      { from: "op1", to: "op2" },
      { from: "op3", to: "op4" },
      { from: "op2", to: "output" },
      { from: "op4", to: "output" },
    ],
  },
  masterGain: 0.76,
  operators: [
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 2,
      fixedHz: 440,
      detune: 0,
      level: 0.42,
      modulationIndex: 1.2,
      feedback: 0,
      envelope: { attack: 0, decay: 0.85, sustain: 0.08, release: 0.4 },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 1,
      fixedHz: 440,
      detune: 0,
      level: 0.95,
      modulationIndex: 0,
      feedback: 0,
      envelope: { attack: 0.003, decay: 1.8, sustain: 0.32, release: 1 },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 3,
      fixedHz: 440,
      detune: 0,
      level: 0.28,
      modulationIndex: 1.45,
      feedback: 0,
      envelope: { attack: 0, decay: 0.18, sustain: 0, release: 0.12 },
    },
    {
      enabled: true,
      waveform: "sine",
      frequencyMode: "ratio",
      ratio: 1,
      fixedHz: 440,
      detune: 3,
      level: 0.32,
      modulationIndex: 0,
      feedback: 0,
      envelope: { attack: 0.002, decay: 0.65, sustain: 0.08, release: 0.55 },
    },
  ],
};
